apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    env: prod
    app: postgres
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: 'postgres:13.1-alpine'
        name: postgres
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresal/data
      volumes:
        - name:
          hostpath:
            path: /data_k8s/postgres
     