apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  labels:
    env: prod
    app: ic-webapp
    name: ic-webapp
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - image: training/ic-webapp:v1
        name: ic-webapp 
        env:
        - name: ODOO_URL
          value: http://192.168.72.16.:30069
        - name: PGADMIN_URL
          value: http://192.168.72.16.:30050
        ports:
        - containerPort: 8080
          name: ic-webapp