apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  labels:
    env: prod
    app: ic-webapp
  namespace: ic-webapp
spec:
  type: NodePort
  selector:
    # app: ic-webapp
    app.kubernetes.io/app: ic-webapp
  ports:
    - port: 8080
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30080