apiVersion: v1
kind: ConfigMap
data:
  servers.json: |
  {
    "servers":{
      "1":{
        "Name":"docker_postgres",
        "Group":"docker-_ostgres-group",
        "Host":"postgres",
        "Port":"5432",
        "MaintenanceDB":"postgres",
        "UserName":"odoo_user",
        "SSLMode":"prefer",
      }
    }
  }
metadata:
  name: pgadmin-config
  namespace: ic-webapp
  labels:
    env: prod

