apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  namespace: ic-webapp
  labels:
    env: prod
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data-k8s/lib-odoo"